spring.application.name=agenda_personal

# PostgreSQL (Tu base de datos al final, yo lo llame agenda)
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda
spring.datasource.driver-class-name=org.postgresql.Driver
# Tus datos:
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Por defecto el 8081, sino funciona pcomentar este y usar el otro
server.port=8080 
#server.port=8081